### ISSUE TITLE
Some code review suggestions

### ISSUE THREAD

**Issue by balhoff** [calliem/compute-expect#8]
Links to source lines are followed by comments:

https://github.com/calliem/compute-expect/blob/master/src/main/java/org/phenoscape/owl/sim/ExpectScoreComputer.java#L14-L20
This may be personal opinion, but I think it is cleaner to make some of these variables local to the methods where they are used, rather then modifying and accessing them from various places. Pass them into the methods that need to read them.

https://github.com/calliem/compute-expect/blob/master/src/main/java/org/phenoscape/owl/sim/ExpectScoreComputer.java#L20
This should be calculated as the number of corpus profiles.

https://github.com/calliem/compute-expect/blob/master/src/main/java/org/phenoscape/owl/sim/ExpectScoreComputer.java#L28
The size of this map is the size of the corpus. Use this instead of the hardcoded `numTaxa`.

**Comment by balhoff** [comment]
I would spend some time removing commented out code. It makes things hard to read, and you can go back to previous versions using Git.

**Comment by calliem** [comment]
I removed most of the global variables and passed them in as parameters instead. I left a few remaining ones (x, y, and identifiers) since they are accessed in multiple methods and are created from just one. If you feel it would be cleaner with them as local variables, I can go back and add more methods to return them as local variables instead.

NumTaxa is now calculated from the size of the corpusProfileSizes map instead of hardcoded. Additionally, I've added a unit test for expect score computation of 20 random data points (that is compared back to the same data points run through the python script). It requires test txt files in the /data directory to run (which should allow for more data points if one wants to generate more random data points in the python script to test).
